<?xml version="1.0" encoding="utf-8"?>
<!-- License: GPL. For details, see LICENSE file. -->
<ivy-module version="2.0">
    <info organisation="org.openstreetmap.josm.plugins" module="importvec"/>
    <dependencies>
        <dependency org="com.formdev" name="svgSalamander" rev="1.1.4"/>
    </dependencies>
</ivy-module>
